#include <minishell.h>

/**
 * @brief Print an error message to stderr in the format "minishell: ctx: msg\n"
 * @param ctx The context of the error (e.g. command name)
 * @param msg The error message to display (if NULL, uses strerror(errno))
 */
void	ms_perror(char *ctx, char *msg)
{
	ft_putstr_fd("minishell: ", 2);
	ft_putstr_fd(ctx, 2);
	ft_putstr_fd(": ", 2);
	if (msg)
		ft_putstr_fd(msg, 2);
	else
		ft_putstr_fd(strerror(errno), 2);
	ft_putstr_fd("\n", 2);
}

/**
 * @brief Handle errors that occur during command execution in a child process.
 * This function prints an error message based on the current value of errno,
 * performs necessary cleanup, and exits with an appropriate exit code.
 * @param cmd The command that caused the error (used for error 
 * message context).
 * @param shell The shell instance, used for cleanup operations.
 */
void	exit_with_exec_error(char *cmd, t_shell *shell)
{
	ms_perror(cmd, strerror(errno));
	cleanup_child_process(shell);
	if (errno == ENOENT)
		exit(127);
	else if (errno == EACCES)
		exit(126);
	else
		exit(1);
}

/**
 * @brief Validates the token list for syntax errors before parsing.
 * @param tokens The list of tokens generated by the lexer
 * @param input The original input line for error messages
 * @return 1 if a syntax error is found, 0 otherwise
 */
int	check_syntax_errors(t_token *tokens, char *input)
{
	if (!tokens)
		return (0);
	if (is_pipe_op(tokens->type))
	{
		print_syntax_error(pipe_op_str(tokens->type), input);
		return (1);
	}
	return (check_middle_and_trailing(tokens, input));
}

/**
 * @brief Prints the two-line bash-style syntax error (token + command hint).
 * @param op The unexpected operator/token that caused the error
 * @param input The original input line for the command hint
 */
void	print_syntax_error(char *op, char *input)
{
	ft_putstr_fd("minishell: syntax error near unexpected token `", 2);
	ft_putstr_fd(op, 2);
	ft_putendl_fd("'", 2);
	if (!isatty(STDIN_FILENO))
	{
		ft_putstr_fd("minishell: `", 2);
		ft_putstr_fd(input, 2);
		ft_putendl_fd("'", 2);
	}
}
